version: "3.8"
services:
    #Database Server
    database:
        image: mysql:8.0
        container_name: mysql
        ports:
            - 3366:3306
        environment:
            - MYSQL_DATABASE:${DB_DATABASE}
            - MYSQL_USER:${DB_USERNAME}
            - MYSQL_PASSWORD:${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD:hellorootpadfvdfvbgffgssword
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_RANDOM_ROOT_PASSWORD=1
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            -   "3400:80"
        depends_on:
            - database
volumes:
    db-data: ~
